version: '3.4'

services:
  stocqres.api:
    image: ${DOCKER_REGISTRY}stocqresapi
    build:
      context: .
      dockerfile: Stocqres.Api/Dockerfile
    links:
      - mongoDb
      - sqlServer

  sqlServer:
    image: microsoft/mssql-server-linux:latest
    container_name: "sqlServer"
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - '20:1433'
    working_dir: /usr/src/app
    volumes:
      - /var/opt/mssql
      - ./scripts/SqlServer:/usr/src/app
    command: bash -c "sh entrypoint.sh & /opt/mssql/bin/sqlservr"

  mongoDb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodata:

