version: '3.4'

services:
  stocqres.api:
    image: ${DOCKER_REGISTRY}stocqresapi
    build:
      context: .
      dockerfile: Stocqres.Api/Dockerfile
    links:
      - mongoDb

  mongoDb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodata: