version: "3"
services:
    postgres: 
        image: clkao/postgres-plv8
        container_name: event-sourcing-net-postgres
        environment:
            - postgres/variables.env
        ports:
            - "5432:5432"
    mongo:
        image: mongo:latest
        container_name: "mongodb"
        volumes:
          - mongodata:/data/db
        ports:
          - '27017:27017'