version: '3.4'

services:
  stocqres.api:
    image: ${DOCKER_REGISTRY}stocqresapi
    build:
      context: .
      dockerfile: Stocqres.Api/Dockerfile
    links:
      - postgres
      - mongoDb

  postgres: 
    image: clkao/postgres-plv8
    container_name: event-sourcing-net-postgres
    environment:
      POSTGRES_PASSWORD: Password12!
    ports:
      - "5432:5432"

  sqlServer:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

  mongoDb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodata: